import re
from pathlib import Path
from typing import List
from concurrent.futures import ThreadPoolExecutor
from crewai import Agent, Crew, Process, Task
from crewai.project import CrewBase, agent, task, crew
from crewai.agents.agent_builder.base_agent import BaseAgent



@CrewBase
class SecurityCrew():
    """
    Class representing a crew of agents for code review
    """
    agents: List[BaseAgent]
    tasks: List[Task]

    agents_config = "config/agents.yaml"
    tasks_config = "config/tasks.yaml"

    @agent
    """
    Security Analyzer: Responsible for analyzing the code for security vulnerabilities
    """
    def security_analyzer(self) -> Agent:
        return Agent(
            config=self.agents_config['security_analyzer'],
            verbose=True,
            allow_delegation=False,
        )

    @agent
    """
    Performance Profiler: Responsible for analyzing the code for performance issues
    """
    def performance_profiler(self) -> Agent:
        return Agent(
            config=self.agents_config['performance_profiler'],
            verbose=True,
            allow_delegation=False,
        )

    @agent
    """
    Bug Detector: Responsible for identifying bugs and logical errors in the code
    """
    def bug_detector(self) -> Agent:
        return Agent(
            config=self.agents_config['bug_detector'],
            verbose=True,
            allow_delegation=False,
        )

    @agent
    """
    Style Reviewer: Responsible for reviewing the code for style and best practices
    """
    def style_reviewer(self) -> Agent:
        return Agent(
            config=self.agents_config['style_reviewer'],
            verbose=True,
            allow_delegation=False,
        )

    @agent
    """
    Review Leader: Responsible for leading the code review process and coordinating between All agents
    """
    def review_leader(self) -> Agent:
        return Agent(
            config=self.agents_config['review_leader'],
            verbose=True,
            allow_delegation=False,
        )

    @task
    """
    Security Audit Task: Task for performing a security audit on the code
    """
    def security_audit_task(self) -> Task:
        return Task(
            config=self.tasks_config["security_audit_task"],
            output_file="output/security_report.md",
        )

    @task
    """
    Bug Detection Task: Task for identifying bugs and logical errors in the code
    """
    def bug_detection_task(self) -> Task:
        return Task(
            config=self.tasks_config["bug_detection_task"],
            output_file="output/bug_report.md",
        )

    @task
    """
    Performance Analysis Task: Task for analyzing the code for performance issues
    """
    def performance_analysis_task(self) -> Task:
        return Task(
            config=self.tasks_config["performance_analysis_task"],
            output_file="output/performance_report.md",
        )

    @task
    """
    Style Review Task: Task for reviewing the code for style and best practices
    """
    def style_review_task(self) -> Task:
        return Task(
            config=self.tasks_config["style_review_task"],
            output_file="output/style_report.md",
        )

    @task
    """
    Final Report Task: Task for generating the final report summarizing all findings
    """
    def final_report_task(self) -> Task:
        return Task(
            config=self.tasks_config["final_report_task"],
            output_file="output/final_report.md",
        )

    @crew
    """
    Crew: Combines all agents and tasks into a cohesive unit for executing the code review process
    """
    def crew(self) -> Crew:
        """Cria e junta a equipa na ordem sequencial correta"""
        return Crew(
            agents=self.agents,
            tasks=self.tasks,
            process=Process.sequential,
            verbose=True,
        )

    def _read_output(self, filename: str) -> str:
        """Helper method to read the output files generated by the agents"""
        path = Path(__file__).parent.parent / filename

        if path.exists():
            return path.read_text(encoding="utf-8")
        return ""

    def _parse_score(self, final_report: str) -> int | None:
        """Helper method to parse the overall health score from the final report"""
        match = re.search(r'(?:Overall Health Score|Health Score)[^\d]*(\d{1,3})', final_report)
        if match:
            return int(match.group(1))
        return None

    def _run_crew(self, agent, task, inputs: dict):
        """Helper method to run a crew with a single agent and task"""
        Crew(
            agents=[agent],
            tasks=[task],
            process=Process.sequential,
            verbose=True,
        ).kickoff(inputs=inputs)

    def run(self, bundle: dict) -> dict:
        """Main method to run the crew with the provided code bundle and return the results"""
        inputs = {
            "code_bundle": bundle["code_bundle"],
            "repo_url": ", ".join(bundle["files_included"]) or "pasted snippet",
        }

        with ThreadPoolExecutor(max_workers=4) as executor:
            futures = [
                executor.submit(
                    self._run_crew,
                    self.security_analyzer(),
                    self.security_audit_task(),
                    inputs,
                ),
                executor.submit(
                    self._run_crew,
                    self.bug_detector(),
                    self.bug_detection_task(),
                    inputs,
                ),
                executor.submit(
                    self._run_crew,
                    self.performance_profiler(),
                    self.performance_analysis_task(),
                    inputs,
                ),
                executor.submit(
                    self._run_crew,
                    self.style_reviewer(),
                    self.style_review_task(),
                    inputs,
                ),
            ]
            for f in futures:
                f.result()

        self._run_crew(self.review_leader(), self.final_report_task(), inputs)

        return {
            "bug_report": self._read_output("output/bug_report.md"),
            "security_report": self._read_output("output/security_report.md"),
            "style_report": self._read_output("output/style_report.md"),
            "performance_report": self._read_output("output/performance_report.md"),
            "final_report": self._read_output("output/final_report.md"),
            "overall_score": self._parse_score(
                self._read_output("output/final_report.md")
            ),
        }
